name: Track Render Deployment

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Render Deployment
        run: |
          curl -X POST "$RENDER_DEPLOY_HOOK"

      - name: Update README with Deploy URL
        run: |
          echo "## Deployment Details" > deployment-info.md
          echo "- **Last Deployed:** $(date)" >> deployment-info.md
          echo "- **Deployed URL:** ${{ secrets.RENDER_DEPLOY_URL }}" >> deployment-info.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add deployment-info.md
          git commit -m "Updated deployment info [skip ci]" || echo "No changes to commit"
          git push
